/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiList: typeof import('./components/ApiList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconDevice: typeof import('./components/icons/IconDevice.vue')['default']
    IconGrid: typeof import('./components/icons/IconGrid.vue')['default']
    IconHome: typeof import('./components/icons/IconHome.vue')['default']
    IconList: typeof import('./components/icons/IconList.vue')['default']
    IconMusicNext: typeof import('./components/icons/IconMusicNext.vue')['default']
    IconMusicPause: typeof import('./components/icons/IconMusicPause.vue')['default']
    IconMusicPlay: typeof import('./components/icons/IconMusicPlay.vue')['default']
    IconMusicPrev: typeof import('./components/icons/IconMusicPrev.vue')['default']
    IconPlay: typeof import('./components/icons/IconPlay.vue')['default']
    IconRandom: typeof import('./components/icons/IconRandom.vue')['default']
    IconRepeatAll: typeof import('./components/icons/IconRepeatAll.vue')['default']
    IconRepeatOne: typeof import('./components/icons/IconRepeatOne.vue')['default']
    IconShrink: typeof import('./components/icons/IconShrink.vue')['default']
    IconStar: typeof import('./components/icons/IconStar.vue')['default']
    IconTimer: typeof import('./components/icons/IconTimer.vue')['default']
    ModalDialog: typeof import('./components/ModalDialog.vue')['default']
    Player: typeof import('./components/player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
