/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiList: typeof import('./components/ApiList.vue')['default']
    AudioPlayer: typeof import('./components/AudioPlayer.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconGrid: typeof import('./components/icons/IconGrid.vue')['default']
    IconHome: typeof import('./components/icons/IconHome.vue')['default']
    IconList: typeof import('./components/icons/IconList.vue')['default']
    IconMusicNext: typeof import('./components/icons/IconMusicNext.vue')['default']
    IconMusicPause: typeof import('./components/icons/IconMusicPause.vue')['default']
    IconMusicPlay: typeof import('./components/icons/IconMusicPlay.vue')['default']
    IconMusicPrev: typeof import('./components/icons/IconMusicPrev.vue')['default']
    IconPlay: typeof import('./components/icons/IconPlay.vue')['default']
    IconRandom: typeof import('./components/icons/IconRandom.vue')['default']
    IconRepeatAll: typeof import('./components/icons/IconRepeatAll.vue')['default']
    IconRepeatOne: typeof import('./components/icons/IconRepeatOne.vue')['default']
    IconShrink: typeof import('./components/icons/IconShrink.vue')['default']
    Player: typeof import('./components/player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
